services:
  kiro:
    image: "ghcr.io/neilkuan/quill:latest"
    container_name: quill-kiro
    restart: always
    volumes:
      - ./data/home/agent:/home/agent
      - ./data/config/kiro/config.toml:/etc/quill/config.toml
    environment:
      - QUILL_LOG=debug
  claude:
    image: "ghcr.io/neilkuan/quill-claude:latest"
    container_name: quill-claude
    restart: always
    volumes:
      - ./data/home/node:/home/node
      - ./data/config/claude/config.toml:/etc/quill/config.toml
    environment:
      - QUILL_LOG=debug
